const Transaction = require('../models/Transaction');
const accountService = require('./accountService');
const { v4: uuidv4 } = require('uuid');

class TransactionService {
  /**
     * Create and process a transaction
        */
          async createTransaction(transactionData) {
              const transaction = new Transaction({
                    transactionId: uuidv4(),
                          fromAccount: transactionData.fromAccount,
                                toAccount: transactionData.toAccount,
                                      amount: transactionData.amount,
                                            currency: transactionData.currency || 'USD',
                                                  type: transactionData.type,
                                                        description: transactionData.description,
                                                              metadata: {
                                                                      ip: transactionData.ip,
                                                                              userAgent: transactionData.userAgent,
                                                                                    },
                                                                                        });

                                                                                            await transaction.save();

                                                                                                // Process the transaction
                                                                                                    try {
                                                                                                          await this.processTransaction(transaction);
                                                                                                              } catch (error) {
                                                                                                                    transaction.status = 'failed';
                                                                                                                          await transaction.save();
                                                                                                                                throw error;
                                                                                                                                    }
                                                                                                                                    
                                                                                                                                        return transaction;
                                                                                                                                          }
                                                                                                                                          
                                                                                                                                            /**
                                                                                                                                               * Process a transaction by updating account balances
                                                                                                                                                  */
                                                                                                                                                    async processTransaction(transaction) {
                                                                                                                                                        // Deduct from source account
                                                                                                                                                            await accountService.updateBalance(transaction.fromAccount, -transaction.amount);
                                                                                                                                                            
                                                                                                                                                                // Credit to destination account (if transfer)
                                                                                                                                                                    if (transaction.toAccount) {
                                                                                                                                                                          await accountService.updateBalance(transaction.toAccount, transaction.amount);
                                                                                                                                                                              }
                                                                                                                                                                              
                                                                                                                                                                                  return transaction.complete();
                                                                                                                                                                                    }
                                                                                                                                                                                    
                                                                                                                                                                                      /**
                                                                                                                                                                                         * Get transactions for an account
                                                                                                                                                                                            * BUG: No pagination - returns ALL transactions regardless of count
                                                                                                                                                                                               * For accounts with thousands of transactions, this will be extremely slow
                                                                                                                                                                                                  * and could cause memory issues
                                                                                                                                                                                                     */
                                                                                                                                                                                                       async getAccountTransactions(accountId) {
                                                                                                                                                                                                           // BUG: No limit, no pagination, no cursor - returns everything
                                                                                                                                                                                                               return Transaction.findByAccount(accountId);
                                                                                                                                                                                                                 }
                                                                                                                                                                                                                 
                                                                                                                                                                                                                   /**
                                                                                                                                                                                                                      * Get a single transaction by ID
                                                                                                                                                                                                                         */
                                                                                                                                                                                                                           async getTransaction(transactionId) {
                                                                                                                                                                                                                               const transaction = await Transaction.findOne({ transactionId });
                                                                                                                                                                                                                                   if (!transaction) {
                                                                                                                                                                                                                                         const error = new Error('Transaction not found');
                                                                                                                                                                                                                                               error.statusCode = 404;
                                                                                                                                                                                                                                                     throw error;
                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                             return transaction;
                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                 /**
                                                                                                                                                                                                                                                                    * Reverse a transaction
                                                                                                                                                                                                                                                                       */
                                                                                                                                                                                                                                                                         async reverseTransaction(transactionId, reason) {
                                                                                                                                                                                                                                                                             const transaction = await this.getTransaction(transactionId);
                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                 if (transaction.status !== 'completed') {
                                                                                                                                                                                                                                                                                       const error = new Error('Can only reverse completed transactions');
                                                                                                                                                                                                                                                                                             error.statusCode = 400;
                                                                                                                                                                                                                                                                                                   throw error;
                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                           // Reverse the balance changes
                                                                                                                                                                                                                                                                                                               await accountService.updateBalance(transaction.fromAccount, transaction.amount);
                                                                                                                                                                                                                                                                                                                   if (transaction.toAccount) {
                                                                                                                                                                                                                                                                                                                         await accountService.updateBalance(transaction.toAccount, -transaction.amount);
                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                 return transaction.reverse(reason);
                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                     /**
                                                                                                                                                                                                                                                                                                                                        * Flag a suspicious transaction
                                                                                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                                                                                             async flagTransaction(transactionId, reason) {
                                                                                                                                                                                                                                                                                                                                                 const transaction = await this.getTransaction(transactionId);
                                                                                                                                                                                                                                                                                                                                                     transaction.status = 'flagged';
                                                                                                                                                                                                                                                                                                                                                         transaction.metadata.flagReason = reason;
                                                                                                                                                                                                                                                                                                                                                             return transaction.save();
                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                 /**
                                                                                                                                                                                                                                                                                                                                                                    * Get transaction summary for reporting
                                                                                                                                                                                                                                                                                                                                                                       * TODO: This is very slow - needs aggregation pipeline
                                                                                                                                                                                                                                                                                                                                                                          */
                                                                                                                                                                                                                                                                                                                                                                            async getTransactionSummary(accountId, startDate, endDate) {
                                                                                                                                                                                                                                                                                                                                                                                const transactions = await Transaction.find({
                                                                                                                                                                                                                                                                                                                                                                                      $or: [{ fromAccount: accountId }, { toAccount: accountId }],
                                                                                                                                                                                                                                                                                                                                                                                            createdAt: { $gte: startDate, $lte: endDate },
                                                                                                                                                                                                                                                                                                                                                                                                  status: 'completed',
                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                          // BUG: Doing aggregation in application code instead of database
                                                                                                                                                                                                                                                                                                                                                                                                              let totalDebit = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                  let totalCredit = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                          transactions.forEach(t => {
                                                                                                                                                                                                                                                                                                                                                                                                                                if (t.fromAccount.toString() === accountId.toString()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        totalDebit += t.amount;
                                                                                                                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      totalCredit += t.amount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          totalDebit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                totalCredit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      netFlow: totalCredit - totalDebit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transactionCount: transactions.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  period: { startDate, endDate },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        module.exports = new TransactionService();
