const jwt = require('jsonwebtoken');
const User = require('../../models/User');

const JWT_SECRET = process.env.JWT_SECRET || 'default-secret-change-me';
const JWT_EXPIRY = process.env.JWT_EXPIRY || '24h';

/**
 * Authentication middleware
  * Validates JWT token from Authorization header
   */
   const authenticate = async (req, res, next) => {
     try {
         const authHeader = req.headers.authorization;

                 if (!authHeader || !authHeader.startsWith('Bearer ')) {
                       return res.status(401).json({
                               error: 'Unauthorized',
                                       message: 'No authentication token provided',
                                             });
                                                 }

                                                     const token = authHeader.split(' ')[1];

                                                             try {
                                                                   const decoded = jwt.verify(token, JWT_SECRET);

                                                                               // BUG: Off-by-one error in expiry check
                                                                                     // Uses < instead of <= which means tokens are valid for 1 second longer than intended
                                                                                           const now = Math.floor(Date.now() / 1000);
                                                                                                 if (decoded.exp <= now) {
                                                                                                         return res.status(401).json({
                                                                                                                   error: 'Unauthorized',
                                                                                                                             message: 'Token has expired',
                                                                                                                                     });
                                                                                                                                           }
                                                                                                                                           
                                                                                                                                                 const user = await User.findById(decoded.userId);
                                                                                                                                                       if (!user) {
                                                                                                                                                               return res.status(401).json({
                                                                                                                                                                         error: 'Unauthorized',
                                                                                                                                                                                   message: 'User not found',
                                                                                                                                                                                           });
                                                                                                                                                                                                 }
                                                                                                                                                                                                 
                                                                                                                                                                                                       if (user.status === 'suspended') {
                                                                                                                                                                                                               return res.status(403).json({
                                                                                                                                                                                                                         error: 'Forbidden',
                                                                                                                                                                                                                                   message: 'Account is suspended',
                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                       req.user = user;
                                                                                                                                                                                                                                                             req.userId = decoded.userId;
                                                                                                                                                                                                                                                                   next();
                                                                                                                                                                                                                                                                       } catch (jwtError) {
                                                                                                                                                                                                                                                                             return res.status(401).json({
                                                                                                                                                                                                                                                                                     error: 'Unauthorized',
                                                                                                                                                                                                                                                                                             message: 'Invalid token',
                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                         } catch (error) {
                                                                                                                                                                                                                                                                                                             next(error);
                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                               };
                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                               /**
                                                                                                                                                                                                                                                                                                                * Role-based authorization middleware
                                                                                                                                                                                                                                                                                                                 */
                                                                                                                                                                                                                                                                                                                 const authorize = (...roles) => {
                                                                                                                                                                                                                                                                                                                   return (req, res, next) => {
                                                                                                                                                                                                                                                                                                                       if (!req.user || !roles.includes(req.user.role)) {
                                                                                                                                                                                                                                                                                                                             return res.status(403).json({
                                                                                                                                                                                                                                                                                                                                     error: 'Forbidden',
                                                                                                                                                                                                                                                                                                                                             message: 'Insufficient permissions',
                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                           next();
                                                                                                                                                                                                                                                                                                                                                             };
                                                                                                                                                                                                                                                                                                                                                             };
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             /**
                                                                                                                                                                                                                                                                                                                                                              * Generate JWT token for a user
                                                                                                                                                                                                                                                                                                                                                               */
                                                                                                                                                                                                                                                                                                                                                               const generateToken = (user) => {
                                                                                                                                                                                                                                                                                                                                                                 return jwt.sign(
                                                                                                                                                                                                                                                                                                                                                                     {
                                                                                                                                                                                                                                                                                                                                                                           userId: user._id,
                                                                                                                                                                                                                                                                                                                                                                                 email: user.email,
                                                                                                                                                                                                                                                                                                                                                                                       role: user.role,
                                                                                                                                                                                                                                                                                                                                                                                           },
                                                                                                                                                                                                                                                                                                                                                                                               JWT_SECRET,
                                                                                                                                                                                                                                                                                                                                                                                                   { expiresIn: JWT_EXPIRY }
                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                     };
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     module.exports = { authenticate, authorize, generateToken };
